### ISSUE TITLE
Unable to clear SCM sync errors from the SCM sync status section in the Jenkins footer

### ISSUE THREAD

**Issue by s-p-turner** [embeddedartistry/scm-sync-configuration-plugin#5]
SCM sync has an option to display its status in the Jenkins footer, and if an error occurs, a hyperlink is displayed to allow an admin user to clear the error by calling the javascript:removeLog() function in the footer.jelly file.

I noticed that the text containing the hyperlink was being displayed literally in the Jenkins footer, meaning that the link wasn't clickable and the error couldn't be cleared. It turns out that hyperlinks (and line breaks) are not being interpreted when contained in jelly string variables.

The modifications in this patch fix this issue.

[fix_clear_SCM_sync_error_issue.gz](https://github.com/embeddedartistry/scm-sync-configuration-plugin/files/3178233/fix_clear_SCM_sync_error_issue.gz)

**Comment by phillipjohnston** [comment]
Thanks for your contribution, I will get it merged in.

Interestingly, I haven't noticed that particular link issue myself - I've been successfully clearing sync issues using the footer link.

**Comment by s-p-turner** [comment]
The footer link is literal and not a hyperlink for me. Maybe it's related to the Jenkins revision (I'm using the latest 2.164.3) or the browser (Firefox) - who knows!

**Comment by s-p-turner** [comment]
Before and after:

![scm-sync-status-before](https://user-images.githubusercontent.com/50615664/57706777-4ea5c180-765e-11e9-9cd7-bba5a9e09757.jpg)

![scm-sync-status-after](https://user-images.githubusercontent.com/50615664/57706789-56656600-765e-11e9-9dba-22b014e0bedd.jpg)
